In [7]:
import numpy as np

## DataTypes & Attributes

In [8]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [9]:
type(a1)

numpy.ndarray

In [10]:
a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17 ,18]]])

In [11]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [12]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [13]:
a1.shape

(3,)

In [14]:
a2.shape

(2, 3)

In [15]:
a3.shape

(2, 3, 3)

In [16]:
a1.ndim

1

In [17]:
a2.ndim, a3.ndim

(2, 3)

In [18]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [19]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [20]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [21]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [22]:
# Create a dataframe using a Numpy array

import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [23]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [24]:
ones = np.ones((2, 3))
ones
ones.dtype

dtype('float64')

In [25]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
type(ones)

numpy.ndarray

In [27]:
zeros = np.zeros((2, 3))

In [28]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [30]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[2, 8, 1, 0, 4],
       [3, 5, 2, 8, 5],
       [4, 2, 8, 2, 1]])

In [31]:
random_array2 = np.random.random((5, 3))

In [32]:
random_array2

array([[0.38599941, 0.10466427, 0.21378234],
       [0.15133986, 0.2083616 , 0.93749658],
       [0.09493289, 0.88461185, 0.29974023],
       [0.70580406, 0.02057443, 0.92076355],
       [0.61177753, 0.32123369, 0.65006009]])

In [33]:
random_array3 = np.random.rand(5, 3)
random_array3

array([[0.16178081, 0.47099219, 0.2013499 ],
       [0.14351964, 0.90377219, 0.27530589],
       [0.83901689, 0.4845853 , 0.61277416],
       [0.37965048, 0.02684739, 0.14457327],
       [0.12036856, 0.25601315, 0.02435006]])

In [34]:
# Pseudo-random numbers

np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4


array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [36]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])